version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn test

workflows:
  version: 2
  test_pipeline:
    jobs:
      - build

